Keep DB blocking in place for each service

diff --git a/docker/docker-entrypoint b/docker/docker-entrypoint
--- a/docker/docker-entrypoint
+++ b/docker/docker-entrypoint
@@ -28,28 +28,28 @@ if [ "$1" == "php-fpm" ] || [ "$1" == "php" ] || [ "$1" == "bin/console" ]; then
         composer dump-env dev
     fi
 
-    if [ "$1" == "php-fpm" ]; then
-        echo "Waiting for db to be ready..."
-        ATTEMPTS_LEFT_TO_REACH_DATABASE=60
-        until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || DATABASE_ERROR=$(bin/console dbal:run-sql "SELECT 1" 2>&1); do
-            if [ $? -eq 255 ]; then
-                # If the Doctrine command exits with 255, an unrecoverable error occurred
-                ATTEMPTS_LEFT_TO_REACH_DATABASE=0
-                break
-            fi
-            sleep 1
-            ATTEMPTS_LEFT_TO_REACH_DATABASE=$((ATTEMPTS_LEFT_TO_REACH_DATABASE - 1))
-            echo "Still waiting for db to be ready... Or maybe the db is not reachable. $ATTEMPTS_LEFT_TO_REACH_DATABASE attempts left"
-        done
-
-        if [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ]; then
-            echo "The database is not up or not reachable:"
-            echo "$DATABASE_ERROR"
-            exit 1
-        else
-            echo "The db is now ready and reachable"
+    echo "Waiting for db to be ready..."
+    ATTEMPTS_LEFT_TO_REACH_DATABASE=60
+    until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || DATABASE_ERROR=$(bin/console dbal:run-sql "SELECT 1" 2>&1); do
+        if [ $? -eq 255 ]; then
+            # If the Doctrine command exits with 255, an unrecoverable error occurred
+            ATTEMPTS_LEFT_TO_REACH_DATABASE=0
+            break
         fi
+        sleep 1
+        ATTEMPTS_LEFT_TO_REACH_DATABASE=$((ATTEMPTS_LEFT_TO_REACH_DATABASE - 1))
+        echo "Still waiting for db to be ready... Or maybe the db is not reachable. $ATTEMPTS_LEFT_TO_REACH_DATABASE attempts left"
+    done
 
+    if [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ]; then
+        echo "The database is not up or not reachable:"
+        echo "$DATABASE_ERROR"
+        exit 1
+    else
+        echo "The db is now ready and reachable"
+    fi
+
+    if [ "$1" == "php-fpm" ]; then
         if [ "$( find ./migrations -iname '*.php' -print -quit )" ]; then
             bin/console doctrine:migrations:migrate --no-interaction
         fi
